### ISSUE TITLE
特にリクエストとかではないですが

### ISSUE THREAD

**Issue by bols-blue** [gokoro/zaifexport#1]
pythonなのにTB社が作ってるpython API使わないの？
https://github.com/techbureau/zaifapi

**Comment by gokoro** [comment]
Notification設定をしてないので、気づくのが遅れました。
ccxtを以前から使用していたので、そちらのライブラリに気づいてませんでした。
そちらのライブラリを利用した方がよいか見てみます。

**Comment by gokoro** [comment]
ブランチ作りました。https://github.com/gokoro/zaifexport/tree/use_zaifapi
zaifapiがまだ非公式扱いのようなので、公式採用時にマージします。
マージ対応は #2 で行うことにして、こちらはクローズします。
