### ISSUE TITLE
入出金履歴も取得できないでしょうか？

### ISSUE THREAD

**Issue by tochi316** [gokoro/zaifexport#4]
自作ツールでBTCとJPY以外の入出金履歴の取得ができず困っております。
入出金履歴も取得できるようになりませんでしょうか。

**Comment by gokoro** [comment]
入出金履歴対応は少し待ってください。

**Comment by gokoro** [comment]
入出金履歴対応しましたが、btc,jpy以外取得できないようです。
通貨種別が多いので、--currenciesオプションで絞り込みできるようにしています。
